### ISSUE TITLE
Unmet Dependencies

### ISSUE THREAD

**Issue by definitelysean** [mani2012/BatchQC#10]
I just upgraded R, and I'm reinstalling a bunch of packages. The install is R 3.3.1

I installed BatchQC via devtools, which should have installed all dependencies, but a bunch were missing that I had to install by hand:

- mcmc
- coda
- SparseM
- MatrixModels 

I'm not totally up on R package specification, but it seems like either the configuration is missing an option to install dependencies of dependencies, or else these dependencies should be included explicitly. 

@wevanjohnson It might be a good idea to set up a virtual machine with a build server that tries to install BatchQC (and other CBM packages?) every time a commit is pushed to Github. That way we can ensure packages are easy to install for anyone, regardless of environment.

**Comment by mani2012** [comment]
The standard way to install BatchQC is from the Bioconductor which will install all the dependencies of dependencies as well automatically. Moreover, bioconductor rules don’t allow the dependencies of dependencies to be directly included, as they are supposed to be resolved automatically based on the updates of each of the packages. Also, we have the Bioconductor setup where it automatically builds on all environments (Windows, Mac and Linux) whenever there is an update and I get to see immediately whenever something fails.

 

source("http://bioconductor.org/biocLite.R")

biocLite("BatchQC")

 

Installing using devtools is only meant for developers and you may have to install the dependencies of dependencies manually depending on the R setup.

 

Mani
