### ISSUE TITLE
PCA plot tooltips show incorrect values with ComBat and SVA

### ISSUE THREAD

**Issue by meono** [mani2012/BatchQC#12]
Hi,

I noticed the tooltips on PCA plot show incorrect values for chosen PCs when ComBat or SVA adjusted data is selected:
(EDIT: I just realized that the tooltip shows the PCs from None adjusted data even when ComBat or SVA is selected.)

![image](https://user-images.githubusercontent.com/8055398/45804432-5aeaa200-bcbc-11e8-83fe-c255f63766a3.png)

This was generated with an example data but I get the same issue with my own data.
```
library(BatchQC)
data(example_batchqc_data)
batch <- batch_indicator$V1
condition <- batch_indicator$V2
batchQC(signature_data, batch=batch, condition=condition)
```

I'm using BatchQC_1.8.0 and can send a full session info if you can't replicate it.

(just a personal preference: A tooltip that shows "condition" in stead of "PCs" might be more helpful when there are numerous conditions.)

Also, thanks a lot for this tool.

**Comment by mani2012** [comment]
Hi,

Thanks for bringing this to notice. I just fixed it. The fix should be available in the next build in a day or two.

Thanks,
Mani
